### ISSUE TITLE
REST Upload via Multipart-Form Body/Form URL

### ISSUE THREAD

**Issue by muellerdo** [qbicsoftware/oncostore-proto-project#16]
Heyho QBiC Team,

zurzeit muss man, zumindest soweit ich es verstanden habe bzw. wie ich
es gemacht habe, die Dateien, welche man hochladen will, innerhalb des Docker Containers kopieren bzw. in die VM, auf welcher der Variantstore läuft.

Gibt es Pläne von dem plain/text Body der POST Befehle /genes/upload und
/variants/upload auf ein Multipart-Form Body oder Form URL encoded Body zu wechseln? 

Bzw. könntet ihr darauf eingehen, warum ihr euch für ein plain/text Body mit url:string Variable
entschieden habt? Weil mit den anderen beiden Bodys könnte der User einen direkten File Upload des z.b. VCF machen ohne Zugriffsrechte auf den Oncostore Container haben zu müssen.

Vielen Dank schon mal für eure Zeit!

Viele Grüße,
Dominik

**Comment by christopher-mohr** [comment]
Hi @muellerdo, finally found time to work on this. Could you please have a look at PR #17? Is this how you would have intended to do it?

**Comment by christopher-mohr** [comment]
Solved by PR #17.

**Comment by muellerdo** [comment]
Hi @christopher-mohr ,

I have to apologize for the late reply.

Sadly, I was not able to test this new feature, yet. 
But the code looks nice and is exactly how I would have intended to implement it.

Great work!

**Comment by christopher-mohr** [comment]
Thanks for the feedback @muellerdo!
