### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by christopher-mohr** [qbicsoftware/oncostore-proto-project#5]
Add README content on installation, usage, database scheme, expected formats etc.

**Comment by Zethson** [comment]
We could also use readthedocs ?
I've set it up in the past for a few projects of mine and could do so here as well...

**Comment by christopher-mohr** [comment]
I would definitely like to provide (some) documentation in the repo directly. Do you think it would make sense to have both? Would there be a way to keep it in sync?

**Comment by Zethson** [comment]
The documentation will be build directly from the repository and is automatically synced with every change to the documentation.
You can keep a simple Readme, but provide details via readthedocs.  Thursday, 19 December 2019, 11:30AM +01:00 from Christopher Mohr  notifications@github.com :

**Comment by christopher-mohr** [comment]
In addition I will also provide the documentation of the REST API on SwaggerHub. I will work on the documentation in January.

**Comment by christopher-mohr** [comment]
I consider this as solved. Basic documentation in GitHub, details on readthedocs, and REST API documentation on SwaggerHub available.
