### ISSUE TITLE
Enable automatic conversion of DB scheme to different DBMS

### ISSUE THREAD

**Issue by christopher-mohr** [qbicsoftware/oncostore-proto-project#6]
When we established the automatic conversion to PostgreSQL, I would suggest to trigger this automatically whenever we push changes to the DB scheme. The MySQL DB scheme could serve as a blueprint for all future DBMS supported. 

@Zethson what do you think?

**Comment by Zethson** [comment]
Sure. Great idea.

I'll have to see which services can actually be run as subprocesses.

**Comment by Zethson** [comment]
```
sqlines -s=mysql -t=postgresql -in=mysql.sql
```

We can use sqlines for this. http://www.sqlines.com/download
Direct: http://www.sqlines.com/downloads/sqlines31171_linux.tar.gz

Maybe we can incorporate this into our CI pipeline?
I'll think of ideas :)

**Comment by Zethson** [comment]
List of all supported DB schemes by sqlines:
```

1 | oracle | Oracle
-- | -- | --
2 | sql | Microsoft SQL Server
3 | db2 | IBM DB2 for z/OS and LUW
4 | sybase | Sybase Adaptive Server Enterprise
5 | asa | Sybase Adaptive Server Anywhere, SQL Anywhere
6 | mysql | MySQL
7 | postgresql | PostgreSQL
8 | informix | Informix Dynamic Server, Extended Parallel Server
9 | greenplum | Greenplum
10 | teradata | Teradata
11 | netezza | Netezza
```

**Comment by Zethson** [comment]
Pretty much all tools that I've tried are not robust enough for a reasonable conversion. It would require substantial manual curation afterwards and therefore just manually converting our DB scheme is the best option that we have.

*cries*
