### ISSUE TITLE
mysql compatibility

### ISSUE THREAD

**Issue by Zethson** [qbicsoftware/oncostore-proto-project#7]
Apparently our mariadb scheme is not perfectly compatible with mysql.

If we want any hope of automatically converting our mariadb scheme to postgresql, then this would certainly help, since just about nothing converts mariadb to postgresql directly.

I'm unfortunately pretty positive that manual conversion will be the best solution in the end...

**Comment by christopher-mohr** [comment]
Do you have a list of the current issues (like using the reserved keyword "end")?

**Comment by Zethson** [comment]
Unfortunately no. I don't know whether this exists.
A possible workaround could be to paste your schema line by line into: http://sqlfiddle.com/ and to slowly figure out what needs to be fixed.

**Comment by Zethson** [comment]
As discussed this should not be necessary. We'll just convert between MariaDB and Postgres without any mysql intermediates.
