### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by Zethson** [qbicsoftware/oncostore-proto-project#9]
This repository does not have a license yet. In my opinion every public repository should have a license to be safe against unwanted redistributions and to allow open source development to foster.

**Comment by muellerdo** [comment]
I can suggest the popular GNU General Public License v3.0.

It is widely used, open-source, allow distribution as well as modifications, but ensures further open-access if anyone develops a modified version.

**Comment by Zethson** [comment]
I'm also a huge fan of GPL3, but I guess we have to discuss this with @sven1103 first.

**Comment by christopher-mohr** [comment]
I guess I will bring that up in the next developer call... so this might be decided by next Wednesday.
